"""create emergency_requests table

Revision ID: 240715fec797
Revises: e5da87481a44
Create Date: 2026-04-27 23:21:22.808206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '240715fec797'
down_revision: Union[str, Sequence[str], None] = 'e5da87481a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergencies_user_id'), table_name='emergencies')
    op.drop_table('emergencies')
    op.drop_index(op.f('ix_home_visit_requests_v3_user_id'), table_name='home_visit_requests_v3')
    op.drop_table('home_visit_requests_v3')
    op.add_column('emergency_requests', sa.Column('ambulance_id', sa.UUID(), nullable=True))
    op.add_column('emergency_requests', sa.Column('address', sa.String(), nullable=True))
    op.add_column('emergency_requests', sa.Column('emergency_type', sa.String(), nullable=True))
    op.add_column('emergency_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('emergency_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_emergency_requests_ambulance_service_id'), table_name='emergency_requests')
    op.drop_index(op.f('ix_emergency_requests_patient_id'), table_name='emergency_requests')
    op.drop_constraint(op.f('emergency_requests_ambulance_service_id_fkey'), 'emergency_requests', type_='foreignkey')
    op.drop_constraint(op.f('emergency_requests_patient_id_fkey'), 'emergency_requests', type_='foreignkey')
    op.create_foreign_key(None, 'emergency_requests', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'emergency_requests', 'ambulance_services', ['ambulance_id'], ['id'], ondelete='SET NULL')
    op.drop_column('emergency_requests', 'ambulance_name')
    op.drop_column('emergency_requests', 'message')
    op.drop_column('emergency_requests', 'ambulance_service_id')
    op.drop_column('emergency_requests', 'request_type')
    op.drop_constraint(op.f('home_visits_patient_id_fkey'), 'home_visits', type_='foreignkey')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('messages_receiver_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('patient_profiles', 'high_contrast_enabled')
    op.drop_column('patient_profiles', 'large_text_enabled')
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'patient'::text"))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_location_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_location_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'patient'::text"))
    op.add_column('patient_profiles', sa.Column('large_text_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('patient_profiles', sa.Column('high_contrast_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_receiver_id_fkey'), 'messages', 'users', ['receiver_id'], ['id'])
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(op.f('home_visits_patient_id_fkey'), 'home_visits', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.add_column('emergency_requests', sa.Column('request_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('emergency_requests', sa.Column('ambulance_service_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('emergency_requests', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('emergency_requests', sa.Column('ambulance_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'emergency_requests', type_='foreignkey')
    op.drop_constraint(None, 'emergency_requests', type_='foreignkey')
    op.create_foreign_key(op.f('emergency_requests_patient_id_fkey'), 'emergency_requests', 'users', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('emergency_requests_ambulance_service_id_fkey'), 'emergency_requests', 'ambulance_services', ['ambulance_service_id'], ['id'])
    op.create_index(op.f('ix_emergency_requests_patient_id'), 'emergency_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_emergency_requests_ambulance_service_id'), 'emergency_requests', ['ambulance_service_id'], unique=False)
    op.alter_column('emergency_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('emergency_requests', 'updated_at')
    op.drop_column('emergency_requests', 'emergency_type')
    op.drop_column('emergency_requests', 'address')
    op.drop_column('emergency_requests', 'ambulance_id')
    op.create_table('home_visit_requests_v3',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('complaint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('preferred_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('preferred_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', 'completed', name='homevisitstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('home_visit_requests_v3_doctor_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('home_visit_requests_v3_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('home_visit_requests_v3_pkey'))
    )
    op.create_index(op.f('ix_home_visit_requests_v3_user_id'), 'home_visit_requests_v3', ['user_id'], unique=False)
    op.create_table('emergencies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('emergencies_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('emergencies_pkey'))
    )
    op.create_index(op.f('ix_emergencies_user_id'), 'emergencies', ['user_id'], unique=False)
    # ### end Alembic commands ###
