"""Add accessibility fields

Revision ID: b3fddbb5e1cc
Revises: 66d90e7d1edf
Create Date: 2026-04-29 14:42:11.569595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3fddbb5e1cc'
down_revision: Union[str, Sequence[str], None] = '66d90e7d1edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('high_contrast_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('large_text_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'large_text_enabled')
    op.drop_column('users', 'high_contrast_enabled')
    # ### end Alembic commands ###
